### ISSUE TITLE
Hoverfly v0.17.0

### ISSUE THREAD

**Issue by benjih** [fredrikn/hoverfly-dotnet#5]
Hey @fredrikn,

Wanted to let you know that we have just released the latest version of Hoverfly, v0.17.0. You should be able to find it on nuget.

I just wanted to give you a heads up that the schema has changed. The changes are described in the [release notes](https://github.com/SpectoLabs/hoverfly/releases/tag/v0.17.0).

We have also added the ability to record stateful services by capturing sequences and playing back sequences. This is not enabled by default and requires setting a mode argument when setting Hoverfly to capture mode.

If you have any questions or need help, please let me know. I am happy to help you with this great project.

**Comment by fredrikn** [comment]
I have upgraded to Hoverfly v 1.0.1.
But because no Nuget Package for it, I included the bin files into the Hoverfly .Net Nuget.
